version: "3.1"

networks:
  proxyNet:
  backend:

services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: elTero
      MYSQL_ROOT_PASSWORD: Tero123
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - backend

  app:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/app:/app:delegated
    environment:
      DDBB_NAME: elTero
      DDBB_HOST: db
      DDBB_PASSWORD: Tero123
      PRODUCCION: 1
      VIRTUAL_HOST: tero.liaima.com.ar, liaima.com.ar, https://tero.liaima.com.ar/
    networks:
      - proxyNet
      - backend
    ports:
      - 8080:80
