version: "3.1"

networks:
  proxyNet:
  
services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: elTero
      MYSQL_ROOT_PASSWORD: Tero123
    volumes:
      - ./mysqldata:/var/lib/mysql

  app:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/app:/app:delegated
    environment:
      DDBB_NAME: elTero
      DDBB_HOST: db
      DDBB_PASSWORD: Tero123
      PRODUCCION: 1
      VIRTUAL_HOST: tero.liaima.com.ar
    networks:
      - proxyNet
    ports:
      - 8080:80
